### ISSUE TITLE
It doesn't load, clicking on it does nothing.

### ISSUE THREAD

**Issue by NatParable** [Svintooo/LEShortcutCreator#2]
For the life of me I can't get this to actually start up. I've updated to the latest version of Locale Emulator, and I placed LEShortcutCreator.cmd into the same folder, but clicking on it doesn't bring up anything (and dragging an existing program onto it doesn't create any shortcuts).

Loading up Windows PowerShell and attempting to run it through that (by typing in ".\LEShortcutCreator") brings up the error message:

>'PowerShell' is not recognized as an internal or external command, operable program or batch file.

**Comment by NatParable** [comment]
Ok, now I feel silly. After some googling I managed to solve the issue. Turns out the filepath to Powershell wasn't set in my environment variables for some reason: https://stackoverflow.com/questions/29778121/powershell-is-not-recognized-as-an-internal-or-external-command-operable-progr/65871920#65871920

**Comment by Svintooo** [comment]
I pushed an update that should solve this problem. An error popup should now be displayed if PowerShell cannot be found.
I also hardcoded the default PowerShell location as a fallback.

Thank you for the report! I really didn't like that this scenario could happen. There are probably other (less technical) users getting confused by the same problem.
